import { MigrationInterface, QueryRunner } from "typeorm";

export class RecreateAllTables1759330146541 implements MigrationInterface {
    name = 'RecreateAllTables1759330146541'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP CONSTRAINT "FK_974f0493cb1bb0c7f945b1a4c8a"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP CONSTRAINT "FK_5669042d7a70b7b61b347d60dde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_222403f87451dcd0cf884b2b76"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP CONSTRAINT "UQ_a84f2b3dad6206bee53a104e0cd"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP CONSTRAINT "UQ_0f21c38accc5cec951990707536"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP COLUMN "championshipApiFootballId"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP COLUMN "minRank"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP COLUMN "maxRank"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "api_football_id"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "league_logo_url"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "country_name"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "country_flag_url"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "stadium"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "espn_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "api_football_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "UQ_5e7d5f2d0ade7b773af24ef70ae"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "api_football_fixture_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "home_team_api_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "away_team_api_id"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "championshipApiFootballId"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "teamApiId"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "teamName"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "teamLogoUrl"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "goalsDiff"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "goalsFor"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "goalsAgainst"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "lastUpdate"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP COLUMN "team1Id"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP COLUMN "team2Id"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP COLUMN "lastUpdated"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD "min_rank" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD "max_rank" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD "championship_id" integer`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "abbreviation" character varying`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "logo_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pool_participants" ADD "paid" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "api_espn_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "venue_name" character varying`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "venue_city" character varying`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "home_team_espn_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "away_team_espn_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "api_espn_status_detail" character varying`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "championship_id" integer`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "team_espn_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "team_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "team_logo_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "goals_diff" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "goals_for" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "goals_against" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "championship_id" integer`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD "team_1_espn_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD "team_2_espn_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD "summary" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "api_espn_id"`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "api_espn_id" integer`);
        await queryRunner.query(`ALTER TABLE "championships" ADD CONSTRAINT "UQ_70c631fc4172d16bfc7f9c9c029" UNIQUE ("api_espn_id")`);
        await queryRunner.query(`ALTER TABLE "championships" ALTER COLUMN "api_espn_slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "base_championship_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."matches_status_enum" RENAME TO "matches_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."matches_status_enum" AS ENUM('SCHEDULED', 'IN_PROGRESS', 'HALFTIME', 'FULL_TIME', 'FINAL', 'POSTPONED', 'CANCELED')`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" TYPE "public"."matches_status_enum" USING "status"::"text"::"public"."matches_status_enum"`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" SET DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`DROP TYPE "public"."matches_status_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4efe722a7d7d78e3ee39b42d16" ON "championships" ("api_espn_slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_24d6a4b277ff034944f714a2d4" ON "matches" ("api_espn_id") `);
        await queryRunner.query(`ALTER TABLE "standings" ADD CONSTRAINT "UQ_c1b677920146077d7b6cf04ae60" UNIQUE ("championship_id", "team_espn_id")`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD CONSTRAINT "UQ_640ca44e807bc10a1e0a6c80400" UNIQUE ("team_1_espn_id", "team_2_espn_id")`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD CONSTRAINT "FK_254b5ee46b0a0d14c4106b566ab" FOREIGN KEY ("championship_id") REFERENCES "championships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pools" ADD CONSTRAINT "FK_0867b2c12e929a47f4f5e312502" FOREIGN KEY ("base_championship_id") REFERENCES "championships"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_8ad570b1c3ccf31a649c5b7e661" FOREIGN KEY ("championship_id") REFERENCES "championships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "standings" ADD CONSTRAINT "FK_5d1bdf0a45322c239e6d89c4958" FOREIGN KEY ("championship_id") REFERENCES "championships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "standings" DROP CONSTRAINT "FK_5d1bdf0a45322c239e6d89c4958"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_8ad570b1c3ccf31a649c5b7e661"`);
        await queryRunner.query(`ALTER TABLE "pools" DROP CONSTRAINT "FK_0867b2c12e929a47f4f5e312502"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP CONSTRAINT "FK_254b5ee46b0a0d14c4106b566ab"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP CONSTRAINT "UQ_640ca44e807bc10a1e0a6c80400"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP CONSTRAINT "UQ_c1b677920146077d7b6cf04ae60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24d6a4b277ff034944f714a2d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4efe722a7d7d78e3ee39b42d16"`);
        await queryRunner.query(`CREATE TYPE "public"."matches_status_enum_old" AS ENUM('TBD', 'NS', '1H', '2H', 'HT', 'FT', 'PST', 'CANC', 'ABD', 'PEN', 'AET')`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" TYPE "public"."matches_status_enum_old" USING "status"::"text"::"public"."matches_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "matches" ALTER COLUMN "status" SET DEFAULT 'TBD'`);
        await queryRunner.query(`DROP TYPE "public"."matches_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."matches_status_enum_old" RENAME TO "matches_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pools" ALTER COLUMN "base_championship_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championships" ALTER COLUMN "api_espn_slug" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championships" DROP CONSTRAINT "UQ_70c631fc4172d16bfc7f9c9c029"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "api_espn_id"`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "api_espn_id" character varying`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP COLUMN "summary"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP COLUMN "team_2_espn_id"`);
        await queryRunner.query(`ALTER TABLE "h2h" DROP COLUMN "team_1_espn_id"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "championship_id"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "goals_against"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "goals_for"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "goals_diff"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "team_logo_url"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "team_name"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP COLUMN "team_espn_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "championship_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "api_espn_status_detail"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "away_team_espn_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "home_team_espn_id"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "venue_city"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "venue_name"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "api_espn_id"`);
        await queryRunner.query(`ALTER TABLE "pool_participants" DROP COLUMN "paid"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "championships" DROP COLUMN "abbreviation"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP COLUMN "championship_id"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP COLUMN "max_rank"`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" DROP COLUMN "min_rank"`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD "lastUpdated" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD "team2Id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD "team1Id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "lastUpdate" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "goalsAgainst" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "goalsFor" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "goalsDiff" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "teamLogoUrl" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "teamName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "teamApiId" integer`);
        await queryRunner.query(`ALTER TABLE "standings" ADD "championshipApiFootballId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "away_team_api_id" integer`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "home_team_api_id" integer`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "api_football_fixture_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "UQ_5e7d5f2d0ade7b773af24ef70ae" UNIQUE ("api_football_fixture_id")`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "api_football_id" integer`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "espn_id" integer`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "stadium" character varying DEFAULT 'Não declarado'`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "country_flag_url" character varying`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "country_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "league_logo_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championships" ADD "api_football_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD "maxRank" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD "minRank" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD "championshipApiFootballId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "h2h" ADD CONSTRAINT "UQ_0f21c38accc5cec951990707536" UNIQUE ("team1Id", "team2Id")`);
        await queryRunner.query(`ALTER TABLE "standings" ADD CONSTRAINT "UQ_a84f2b3dad6206bee53a104e0cd" UNIQUE ("championshipApiFootballId", "teamApiId")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_222403f87451dcd0cf884b2b76" ON "championships" ("api_football_id") `);
        await queryRunner.query(`ALTER TABLE "standings" ADD CONSTRAINT "FK_5669042d7a70b7b61b347d60dde" FOREIGN KEY ("championshipApiFootballId") REFERENCES "championships"("api_football_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "championship_standing_rules" ADD CONSTRAINT "FK_974f0493cb1bb0c7f945b1a4c8a" FOREIGN KEY ("championshipApiFootballId") REFERENCES "championships"("api_football_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
